// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiy8nefmZSBaabr_WKT9h2Amb5Pu0jDM4',
    appId: '1:422032983113:web:38e9857c34fea30fd22b98',
    messagingSenderId: '422032983113',
    projectId: 'cloud-storo',
    authDomain: 'cloud-storo.firebaseapp.com',
    storageBucket: 'cloud-storo.appspot.com',
    measurementId: 'G-ZKNP25SHZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGibHRE-UQHAUbOyB0gHokSS6-fx7vc3Q',
    appId: '1:422032983113:android:8a7541d2ed95f926d22b98',
    messagingSenderId: '422032983113',
    projectId: 'cloud-storo',
    storageBucket: 'cloud-storo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOObGhyLJzK7r7hlCqDJfzo-H8ksg6Lig',
    appId: '1:422032983113:ios:6b63c7bb1981076ed22b98',
    messagingSenderId: '422032983113',
    projectId: 'cloud-storo',
    storageBucket: 'cloud-storo.appspot.com',
    androidClientId: '422032983113-qvg7ogu7d4gqetfq2494a104rcd9vlid.apps.googleusercontent.com',
    iosClientId: '422032983113-mqbrun44r1dfu9bhk55ddjiirnhvvgn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudStoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiy8nefmZSBaabr_WKT9h2Amb5Pu0jDM4',
    appId: '1:422032983113:web:c944a0c7eba51544d22b98',
    messagingSenderId: '422032983113',
    projectId: 'cloud-storo',
    authDomain: 'cloud-storo.firebaseapp.com',
    storageBucket: 'cloud-storo.appspot.com',
    measurementId: 'G-H3MG3N6T7F',
  );

}